spring:
  application:
    name: spotkanie-config
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: file://${HOME}/CoreLogic/Spotkanie/configuration/
          username: admin
          password: admin

server:
  port: 9080

eureka:
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka